version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PACKAGES_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    registries:
      - npm-github
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(deps-dev)'
    ignore:
      - dependency-name: 'react'
      - dependency-name: 'commit-check/commit-check-action'
    open-pull-requests-limit: 100
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'security'
      - 'review needed'
      - 'status: ready'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(deps-dev)'
    open-pull-requests-limit: 100
    labels:
      - 'dependencies'
      - 'security'
      - 'review needed'
      - 'status: ready'
